import { SideBanner } from "@/features/auth/components/side-banner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-1 lg:grid-cols-6 bg-neutral-900 h-screen">
      <div className="col-span-2 hidden lg:block">
        <SideBanner />
      </div>
      <div className="col-span-4 flex items-center justify-center w-full">
        {children}
      </div>
    </div>
  );
}
